### ISSUE TITLE
No clearkey pssh in 2015's ClearKeyVideo test

### ISSUE THREAD

**Issue by moorthy-bs** [youtube/js_mse_eme#31] opened 2018-04-11 10:17 UTC
I observed that only playready pssh of length 848 and widevine pssh of length 193 are with 2015 ClearKeyVideo test's video, however, 'drm-preferred-decryption-system-id' is set to ClearKey UUID. Though preferred ID is clearkey but the browser's EME is picking widevine due to there is no respective pssh. Same I observed also in 2016's ClearKeyAudio

Here is the log for reference
```
0:00:11.988359169 16288  0x169d000 LOG                  qtdemux qtdemux_dump.c:927:qtdemux_node_dump_foreach:   'free', [864], free
0:00:11.988693332 16288  0x169d000 LOG                  qtdemux qtdemux_dump.c:927:qtdemux_node_dump_foreach:   'pssh', [848], protection system specific header
0:00:11.989041661 16288  0x169d000 LOG                  qtdemux qtdemux_dump.c:927:qtdemux_node_dump_foreach:   'pssh', [193], protection system specific header
0:00:11.989374157 16288  0x169d000 LOG                  qtdemux qtdemux_dump.c:927:qtdemux_node_dump_foreach:   'mvex', [40], mvex
0:00:11.989709152 16288  0x169d000 LOG                  qtdemux qtdemux_dump.c:927:qtdemux_node_dump_foreach:     'trex', [32], moovie data
.
.
.
0:00:12.030887798 16288  0x169d000 LOG                  qtdemux qtdemux.c:12975:qtdemux_parse_tree:<qtdemux0> Parsing pssh box.
0:00:12.031255293 16288  0x169d000 DEBUG                qtdemux qtdemux.c:14125:gst_qtdemux_append_protection_system_id:<qtdemux0> Adding cenc protection system ID 9a04f079-9840-4286-ab92-e65be0885f95
0:00:12.031607789 16288  0x169d000 LOG                  qtdemux qtdemux.c:3830:qtdemux_parse_pssh:<qtdemux0> cenc pssh size: 848
0:00:12.032022784 16288  0x169d000 TRACE                qtdemux qtdemux.c:3839:qtdemux_parse_pssh:<qtdemux0> adding protection event for stream 0 and system 9a04f079-9840-4286-ab92-e65be0885f95
0:00:12.032347779 16288  0x169d000 LOG                  qtdemux qtdemux.c:12975:qtdemux_parse_tree:<qtdemux0> Parsing pssh box.
0:00:12.032653609 16288  0x169d000 DEBUG                qtdemux qtdemux.c:14125:gst_qtdemux_append_protection_system_id:<qtdemux0> Adding cenc protection system ID edef8ba9-79d6-4ace-a3c8-27dcd51d21ed
0:00:12.032976105 16288  0x169d000 LOG                  qtdemux qtdemux.c:3830:qtdemux_parse_pssh:<qtdemux0> cenc pssh size: 193
0:00:12.033340267 16288  0x169d000 TRACE                qtdemux qtdemux.c:3839:qtdemux_parse_pssh:<qtdemux0> adding protection event for stream 0 and system edef8ba9-79d6-4ace-a3c8-27dcd51d21ed
```

**Comment by moorthy-bs** [comment] 2018-04-13 11:26
Since this is clearkey test and the stream should have Clearkey's pssh box but only playready and widevine pssh boxes are found. Noted that there is pssh box for clearkey, is there any specific reason for this or a bug?

**Comment by jiaqzhao** [comment] 2018-04-13 19:13
Duplicate of #12

**Closed by jiaqzhao** 2018-04-13 19:13 UTC
